# -*- coding: utf-8 -*-
"""demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Matthew-Matta/hybrid-suffix-speculative-decoding/blob/main/notebooks/demo.ipynb

# Suffix Automaton + Dynamic-Length Speculative Decoding

**Weekend project** — reimplements the core ideas from Baseten's `sa_spec` repo and adds **dynamic draft length control**, the explicit future-work item from their [SA MTP blog post (Jan 27, 2026)](https://www.baseten.co/blog/sa-mtp).

### Five decoding modes
| Mode | Description |
|------|-------------|
| `autoregressive` | Baseline: one target step per token |
| `specdec` | Draft model only (fixed draft length) |
| `sa_only` | Suffix automaton only (fixed draft length) |
| `hybrid_fixed` | SA + draft model, fixed length |
| `hybrid_dynamic` | SA + draft model, **adaptive draft length** (novel) |

**Runtime**: T4 GPU on Google Colab (free tier)

## 1. Setup
"""

!git -C /content/hybrid-suffix-speculative-decoding pull origin main



!pip install -q torch transformers datasets numpy matplotlib tqdm accelerate

import os, sys

REPO_DIR = "hybrid-suffix-speculative-decoding"

if not os.path.isdir(REPO_DIR):
    !git clone https://github.com/Matthew-Matta/hybrid-suffix-speculative-decoding.git

# Add repo root to path so `src` is importable
sys.path.insert(0, REPO_DIR)
os.chdir(REPO_DIR)   # also cd in so relative paths (results/) work
print("Working directory:", os.getcwd())

import torch
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display
import pandas as pd

from transformers import AutoModelForCausalLM, AutoTokenizer

from src.suffix_automaton import SuffixAutomaton, DualSuffixAutomaton
from src.speculative_decode import HybridSpecDecoder
from src.utils import plot_benchmark_results, print_summary_table

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DTYPE  = torch.float16 if DEVICE == "cuda" else torch.float32
print(f"Device: {DEVICE}  |  dtype: {DTYPE}")

"""## 2. Suffix Automaton — unit test

Build from `[1,2,3,1,2]`, query with `[1,2]` → expect draft `[3]`, match_len=2.
"""

sa = SuffixAutomaton()
sa.build([1, 2, 3, 1, 2])

drafts, match_len = sa.query([1, 2], max_draft_len=4)
print(f"Draft tokens : {drafts}")
print(f"Match length : {match_len}")
assert match_len == 2, f"Expected match_len=2, got {match_len}"
assert 3 in drafts, f"Expected token 3 in drafts, got {drafts}"
print("✓  Unit test passed")

"""## 3. Load models"""

TARGET_NAME = "Qwen/Qwen2.5-Coder-1.5B-Instruct"
DRAFT_NAME  = "Qwen/Qwen2.5-Coder-0.5B-Instruct"

print("Loading target model…")
target_tok   = AutoTokenizer.from_pretrained(TARGET_NAME)
target_model = AutoModelForCausalLM.from_pretrained(
    TARGET_NAME, torch_dtype=DTYPE, device_map="auto"
)

print("Loading draft model…")
draft_tok   = AutoTokenizer.from_pretrained(DRAFT_NAME)
draft_model = AutoModelForCausalLM.from_pretrained(
    DRAFT_NAME, torch_dtype=DTYPE, device_map="auto"
)

decoder = HybridSpecDecoder(
    target_model=target_model,
    target_tokenizer=target_tok,
    draft_model=draft_model,
    draft_tokenizer=draft_tok,
    device=DEVICE,
)
print("Models ready.")

# Warm up CUDA kernels — eliminates ~1s first-run latency from TPS measurements
decoder.warmup()
print("CUDA warmup complete.")

"""## 4. Single prompt demo — all five modes"""

DEMO_PROMPT = (
    "Write a Python function that implements binary search on a sorted list. "
    "Include docstring and type hints."
)

MODES = ["autoregressive", "specdec", "sa_only", "hybrid_fixed", "hybrid_dynamic"]
demo_results = {}

for mode in MODES:
    print(f"\n{'='*60}")
    print(f"Mode: {mode}")
    print('='*60)
    text, metrics = decoder.generate(
        prompt=DEMO_PROMPT,
        max_new_tokens=150,
        mode=mode,
        num_draft_tokens=4,
        sa_threshold=2,
    )
    demo_results[mode] = (text, metrics)
    print(text[:400], "…" if len(text) > 400 else "")
    print(f"\n  TPS={metrics.tokens_per_second:.1f}  "
          f"TTFT={metrics.ttft_s:.3f}s  "
          f"accept={metrics.acceptance_rate:.2%}  "
          f"avg_draft_len={metrics.avg_draft_length:.2f}")

rows = []
for mode, (_, m) in demo_results.items():
    rows.append({
        "Mode": mode,
        "TPS": f"{m.tokens_per_second:.1f}",
        "TTFT (s)": f"{m.ttft_s:.4f}",
        "Tokens": m.tokens_generated,
        "Accept %": f"{m.acceptance_rate:.1%}",
        "SA acc %": f"{m.sa_acceptance_rate:.1%}",
        "Draft acc %": f"{m.draft_acceptance_rate:.1%}",
        "Avg draft len": f"{m.avg_draft_length:.2f}",
    })
df = pd.DataFrame(rows)
display(df)

"""## 5. Mini-benchmark — 10 prompts, TPS comparison"""

from src.benchmark import load_dataset, run_benchmark

mini_prompts = load_dataset(n_samples=10)
print(f"Loaded {len(mini_prompts)} prompts for mini-benchmark.")

mini_results = {}
for mode in MODES:
    print(f"Running {mode}…")
    mini_results[mode] = run_benchmark(
        decoder=decoder,
        prompts=mini_prompts,
        method=mode,
        max_new_tokens=80,
        num_draft_tokens=4,
        sa_threshold=2,
    )
print("Done.")

methods = list(mini_results.keys())
mean_tps = [np.mean([m.tokens_per_second for m in mini_results[meth]]) for meth in methods]

fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.bar(methods, mean_tps, color=plt.cm.tab10(np.linspace(0, 0.9, len(methods))))
ax.set_ylabel("Tokens per Second (TPS)")
ax.set_title("Mini-Benchmark TPS — 10 code prompts")
ax.set_xticklabels(methods, rotation=15, ha="right")
for bar, v in zip(bars, mean_tps):
    ax.text(bar.get_x() + bar.get_width()/2, v + 0.2, f"{v:.1f}", ha="center", fontsize=9)
fig.tight_layout()
plt.show()

"""## 6. Dynamic draft length visualisation

Shows how `hybrid_dynamic` adapts the number of speculative tokens over the course of generation.
"""

if "hybrid_dynamic" in mini_results and mini_results["hybrid_dynamic"]:
    # Concatenate histories from all 10 prompts
    all_histories = []
    for m in mini_results["hybrid_dynamic"]:
        all_histories.extend(m.draft_length_history)

    fig, axes = plt.subplots(1, 2, figsize=(14, 4))

    # Left: length over steps
    axes[0].plot(all_histories, linewidth=0.8, alpha=0.8)
    axes[0].axhline(np.mean(all_histories), color="red", linestyle="--",
                    label=f"mean={np.mean(all_histories):.2f}")
    axes[0].set_xlabel("Decoding step (all prompts concatenated)")
    axes[0].set_ylabel("Draft length")
    axes[0].set_title("Adaptive Draft Length — hybrid_dynamic")
    axes[0].legend()

    # Right: histogram
    axes[1].hist(all_histories, bins=range(1, 13), edgecolor="black", color="steelblue", alpha=0.8)
    axes[1].set_xlabel("Draft length")
    axes[1].set_ylabel("Count")
    axes[1].set_title("Draft Length Distribution")

    fig.tight_layout()
    plt.show()
else:
    print("No hybrid_dynamic results available.")

"""## 7. Acceptance rate breakdown"""

print_summary_table(mini_results)

methods = list(mini_results.keys())
sa_rates      = [np.mean([m.sa_acceptance_rate    for m in mini_results[meth]]) for meth in methods]
draft_rates   = [np.mean([m.draft_acceptance_rate for m in mini_results[meth]]) for meth in methods]
overall_rates = [np.mean([m.acceptance_rate       for m in mini_results[meth]]) for meth in methods]

x = np.arange(len(methods))
width = 0.25
fig, ax = plt.subplots(figsize=(9, 5))
ax.bar(x - width, sa_rates,      width, label="SA",      color="steelblue")
ax.bar(x,         draft_rates,   width, label="Draft",   color="darkorange")
ax.bar(x + width, overall_rates, width, label="Overall", color="seagreen")
ax.set_xticks(x)
ax.set_xticklabels(methods, rotation=15, ha="right")
ax.set_ylabel("Acceptance Rate")
ax.set_ylim(0, 1.1)
ax.set_title("Acceptance Rate Breakdown by Source")
ax.legend()
fig.tight_layout()
plt.show()

"""## 8. Save results"""

import os
from src.benchmark import save_results
from src.utils import plot_benchmark_results

os.makedirs("results/figures", exist_ok=True)
save_results(mini_results, path="results/benchmarks.json")
plot_benchmark_results(mini_results, output_dir="results/figures")
print("All results saved.")

import json

with open('results/benchmarks.json') as f:
    data = json.load(f)

for method, runs in data.items():
    tps = sum(r['tokens_per_second'] for r in runs) / len(runs)
    acc = sum(r['acceptance_rate'] for r in runs) / len(runs)
    adl = sum(r['avg_draft_length'] for r in runs) / len(runs)
    print(f"{method:<22} TPS={tps:.1f}  accept={acc:.1%}  avg_draft_len={adl:.2f}")